name: "poetry-buildpack"
description: A typical poetry build steps. Assume you have checkout source already

branding:
  icon: 'package'
  color: 'purple'
inputs:
  tests:
    description: Test Sources Root: working-directory of your tests
    required: false
    default: tests
  test-entry-point:
    description: script of test command, such as pytest
    required: false
  version:
    description: python version, such as 3.12
    required: false
  working-directory:
    description: poetry home path. dirname of file pyproject.toml
    required: true
runs:
  using: "composite"
  steps:
  - if: ${{ inputs.version != '' }}
    uses: actions/setup-python@main
    with:
      python-version: ${{ inputs.version }}
  - uses: snok/install-poetry@main
  - run: poetry install --all-extras
  - if: ${{ inputs.test-entry-point != '' }}
    run: poetry run ${{ inputs.test-entry-point }}
    working-directory: ${{ inputs.tests }}
