[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
davidkhala-utils = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
